# Site settings
title: Sebastian Blaes
description: 'Business Card Page'
url: 'http://s-bl.github.io'
baseurl: ''
profilepic: '/images/s-bl.png'
bkimage: '/images/anastasia-zhenina-E4XARZNDjzI-unsplash.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '/js/all.js'

author:
  name: 'Sebastian Blaes'
  email: sebastianblaes@gmail.com
  # twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  s-bl
  linkedin_username:  sebastian-blaes
  # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
